Zajel.Web/Areas/Admin/Models/OLD/Polls/PollAnswerModel.cs
using Zajel.Framework.Mvc.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Zajel.Framework.Mvc.ModelBinding;
using FluentValidation.Attributes;
using Zajel.Web.Areas.Admin.Validators.Polls;
using Zajel.Framework;
using Zajel.Framework.Mvc;
using Zajel.Framework.Localization;
using System.Collections.Generic;

namespace Zajel.Web.Areas.Admin.Models.Polls
{
    [Validator(typeof(PollAnswerValidator))]
    public partial class PollAnswerModel : BaseZajelEntityModel, ILocalizedModel<PollAnswerLocalizedModel>
    {
        public PollAnswerModel()
        {
            Locales = new List<PollAnswerLocalizedModel>();
        }

        public string PollId { get; set; }

        [ZajelResourceDisplayName("Admin.ContentManagement.Polls.Answers.Fields.Name")]
        
        public string Name { get; set; }

        [ZajelResourceDisplayName("Admin.ContentManagement.Polls.Answers.Fields.NumberOfVotes")]
        public int NumberOfVotes { get; set; }

        [ZajelResourceDisplayName("Admin.ContentManagement.Polls.Answers.Fields.DisplayOrder")]
        public int DisplayOrder { get; set; }

        public IList<PollAnswerLocalizedModel> Locales { get; set; }


    }

    public partial class PollAnswerLocalizedModel : ILocalizedModelLocal
    {
        public string LanguageId { get; set; }

        [ZajelResourceDisplayName("Admin.ContentManagement.Polls.Answers.Fields.Name")]
        
        public string Name { get; set; }
    }


}

Zajel.Web/Areas/Admin/Models/OLD/Polls/PollModel.cs
using Zajel.Framework.Mvc.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Zajel.Framework.Mvc.ModelBinding;
using System;
using System.ComponentModel.DataAnnotations;

using FluentValidation.Attributes;
using Zajel.Web.Areas.Admin.Validators.Polls;
using Zajel.Framework;
using Zajel.Framework.Mvc;
using Zajel.Framework.Localization;
using Zajel.Web.Areas.Admin.Models.Stores;
using System.Collections.Generic;
using Zajel.Web.Areas.Admin.Models.Users;

namespace Zajel.Web.Areas.Admin.Models.Polls
{
    [Validator(typeof(PollValidator))]
    public partial class PollModel : BaseZajelEntityModel, ILocalizedModel<PollLocalizedModel>
    {

        public PollModel()
        {
            AvailableStores = new List<StoreModel>();
            Locales = new List<PollLocalizedModel>();
            AvailableUserRoles = new List<UserRoleModel>();
        }

        [ZajelResourceDisplayName("Admin.ContentManagement.Polls.Fields.Name")]
        
        public string Name { get; set; }

        [ZajelResourceDisplayName("Admin.ContentManagement.Polls.Fields.SystemKeyword")]
        
        public string SystemKeyword { get; set; }

        [ZajelResourceDisplayName("Admin.ContentManagement.Polls.Fields.Published")]
        public bool Published { get; set; }

        [ZajelResourceDisplayName("Admin.ContentManagement.Polls.Fields.ShowOnHomePage")]
        public bool ShowOnHomePage { get; set; }

        [ZajelResourceDisplayName("Admin.ContentManagement.Polls.Fields.AllowGuestsToVote")]
        public bool AllowGuestsToVote { get; set; }

        [ZajelResourceDisplayName("Admin.ContentManagement.Polls.Fields.DisplayOrder")]
        public int DisplayOrder { get; set; }

        [ZajelResourceDisplayName("Admin.ContentManagement.Polls.Fields.StartDate")]
        [UIHint("DateTimeNullable")]
        public DateTime? StartDate { get; set; }

        [ZajelResourceDisplayName("Admin.ContentManagement.Polls.Fields.EndDate")]
        [UIHint("DateTimeNullable")]
        public DateTime? EndDate { get; set; }

        //Store mapping
        [ZajelResourceDisplayName("Admin.ContentManagement.Polls.Fields.LimitedToStores")]
        public bool LimitedToStores { get; set; }
        [ZajelResourceDisplayName("Admin.ContentManagement.Polls.Fields.AvailableStores")]
        public IList<StoreModel> AvailableStores { get; set; }
        public string[] SelectedStoreIds { get; set; }
        public IList<PollLocalizedModel> Locales { get; set; }


        //ACL
        [ZajelResourceDisplayName("Admin.ContentManagement.Polls.Fields.SubjectToAcl")]
        public bool SubjectToAcl { get; set; }
        [ZajelResourceDisplayName("Admin.ContentManagement.Polls.Fields.AclUserRoles")]
        public List<UserRoleModel> AvailableUserRoles { get; set; }
        public string[] SelectedUserRoleIds { get; set; }

    }

    public partial class PollLocalizedModel : ILocalizedModelLocal
    {
        public string LanguageId { get; set; }

        [ZajelResourceDisplayName("Admin.ContentManagement.Polls.Fields.Name")]
        public string Name { get; set; }

    }

}

Zajel.Web/Controllers/OLD/CommonController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Zajel.Core;
using Zajel.Core.Domain;
using Zajel.Core.Domain.Common;
using Zajel.Core.Domain.Users;
using Zajel.Core.Domain.Forums;
using Zajel.Core.Domain.Localization;
using Zajel.Core.Domain.Messages;
using Zajel.Core.Domain.Vendors;
using Zajel.Services.Common;
using Zajel.Services.Users;
using Zajel.Services.Localization;
using Zajel.Services.Logging;
using Zajel.Services.Messages;
using Zajel.Services.Vendors;
using Zajel.Framework.Localization;
using Zajel.Framework.Security;
using Zajel.Framework.Security.Captcha;
using Zajel.Framework.Themes;
using Zajel.Web.Models.Common;
using System.Text.RegularExpressions;
using Zajel.Web.Services;
using Zajel.Core.Infrastructure;
using Microsoft.AspNetCore.Diagnostics;
using Zajel.Framework.Mvc.Filters;
using Microsoft.AspNetCore.Http;

namespace Zajel.Web.Controllers
{
    public partial class CommonController : BasePublicController
    {
        #region Fields
        private readonly ICommonWebService _commonWebService;
        private readonly ILocalizationService _localizationService;
        private readonly IWorkContext _workContext;
        private readonly IStoreContext _storeContext;
        private readonly IUserActivityService _userActivityService;
        private readonly IUserActionEventService _userActionEventService;
        private readonly IPopupService _popupService;
        private readonly IInteractiveFormService _interactiveFormService;
        private readonly ILogger _logger;
        private readonly StoreInformationSettings _storeInformationSettings;
        private readonly CommonSettings _commonSettings;
        private readonly ForumSettings _forumSettings;
        private readonly LocalizationSettings _localizationSettings;
        private readonly CaptchaSettings _captchaSettings;
        private readonly VendorSettings _vendorSettings;

        #endregion

        #region Constructors

        public CommonController(
            ICommonWebService commonWebService,
            ILocalizationService localizationService,
            IWorkContext workContext,
            IStoreContext storeContext,
            IUserActivityService userActivityService,
            IUserActionEventService userActionEventService,
            IPopupService popupService,
            IInteractiveFormService interactiveFormService,
            ILogger logger,
            StoreInformationSettings storeInformationSettings,
            CommonSettings commonSettings,
            ForumSettings forumSettings,
            LocalizationSettings localizationSettings,
            CaptchaSettings captchaSettings,
            VendorSettings vendorSettings
            )
        {
            this._commonWebService = commonWebService;
            this._localizationService = localizationService;
            this._workContext = workContext;
            this._storeContext = storeContext;
            this._userActivityService = userActivityService;
            this._userActionEventService = userActionEventService;
            this._popupService = popupService;
            this._interactiveFormService = interactiveFormService;
            this._logger = logger;
            this._storeInformationSettings = storeInformationSettings;
            this._commonSettings = commonSettings;
            this._forumSettings = forumSettings;
            this._localizationSettings = localizationSettings;
            this._captchaSettings = captchaSettings;
            this._vendorSettings = vendorSettings;
        }

        #endregion

        #region Methods

        //page not found
        public virtual IActionResult PageNotFound()
        {
            if (_commonSettings.Log404Errors)
            {
                var statusCodeReExecuteFeature = HttpContext?.Features?.Get<IStatusCodeReExecuteFeature>();
                //TODO add locale resource
                _logger.Error(string.Format("Error 404. The requested page ({0}) was not found", statusCodeReExecuteFeature?.OriginalPath),
                    user: _workContext.CurrentUser);
            }

            this.Response.StatusCode = 404;
            this.Response.ContentType = "text/html";

            return View();
        }

        //available even when a store is closed
        [CheckAccessClosedStore(true)]
        //available even when navigation is not allowed
        [CheckAccessPublicStore(true)]
        public virtual IActionResult SetLanguage(string langid, string returnUrl = "")
        {

            _commonWebService.SetLanguage(langid);

            //home page
            if (String.IsNullOrEmpty(returnUrl))
                returnUrl = Url.RouteUrl("HomePage");

            //prevent open redirection attack
            if (!Url.IsLocalUrl(returnUrl))
                returnUrl = Url.RouteUrl("HomePage");

            //language part in URL
            if (_localizationSettings.SeoFriendlyUrlsForLanguagesEnabled)
            {
                //remove current language code if it's already localized URL
                if (returnUrl.IsLocalizedUrl(this.Request.PathBase, true, out Language urlLanguage))
                    returnUrl = returnUrl.RemoveLanguageSeoCodeFromUrl(this.Request.PathBase, true);

                //and add code of passed language
                returnUrl = returnUrl.AddLanguageSeoCodeToUrl(this.Request.PathBase, true, _workContext.WorkingLanguage);
            }
            return Redirect(returnUrl);
        }
        //available even when navigation is not allowed
        [CheckAccessPublicStore(true)]
        public virtual IActionResult SetCurrency(string userCurrency, string returnUrl = "")
        {
            _commonWebService.SetCurrency(userCurrency);

            //home page
            if (String.IsNullOrEmpty(returnUrl))
                returnUrl = Url.RouteUrl("HomePage");

            //prevent open redirection attack
            if (!Url.IsLocalUrl(returnUrl))
                returnUrl = Url.RouteUrl("HomePage");

            return Redirect(returnUrl);
        }

        //available even when navigation is not allowed
        [CheckAccessPublicStore(true)]
        public virtual IActionResult SetTaxType(int userTaxType, string returnUrl = "")
        {
            _commonWebService.SetTaxType(userTaxType);

            //home page
            if (String.IsNullOrEmpty(returnUrl))
                returnUrl = Url.RouteUrl("HomePage");

            //prevent open redirection attack
            if (!Url.IsLocalUrl(returnUrl))
                returnUrl = Url.RouteUrl("HomePage");

            return Redirect(returnUrl);
        }

        //contact us page
        [HttpsRequirement(SslRequirement.Yes)]
        //available even when a store is closed
        [CheckAccessClosedStore(true)]
        public virtual IActionResult ContactUs()
        {
            var model = _commonWebService.PrepareContactUs();
            return View(model);
        }

        [HttpPost, ActionName("ContactUs")]
        [PublicAntiForgery]
        [ValidateCaptcha]
        //available even when a store is closed
        [CheckAccessClosedStore(true)]
        public virtual IActionResult ContactUsSend(ContactUsModel model, bool captchaValid)
        {
            //validate CAPTCHA
            if (_captchaSettings.Enabled && _captchaSettings.ShowOnContactUsPage && !captchaValid)
            {
                ModelState.AddModelError("", _captchaSettings.GetWrongCaptchaMessage(_localizationService));
            }

            if (ModelState.IsValid)
            {
                model = _commonWebService.SendContactUs(model);
                //activity log
                _userActivityService.InsertActivity("PublicStore.ContactUs", "", _localizationService.GetResource("ActivityLog.PublicStore.ContactUs"));
                return View(model);
            }
            model.DisplayCaptcha = _captchaSettings.Enabled && _captchaSettings.ShowOnContactUsPage;
            return View(model);
        }
        //contact vendor page
        [HttpsRequirement(SslRequirement.Yes)]
        public virtual IActionResult ContactVendor(string vendorId)
        {
            if (!_vendorSettings.AllowUsersToContactVendors)
                return RedirectToRoute("HomePage");

            var vendor = EngineContext.Current.Resolve<IVendorService>().GetVendorById(vendorId);
            if (vendor == null || !vendor.Active || vendor.Deleted)
                return RedirectToRoute("HomePage");

            var model = _commonWebService.PrepareContactVendor(vendor);

            return View(model);
        }
        [HttpPost, ActionName("ContactVendor")]
        [PublicAntiForgery]
        [ValidateCaptcha]
        public virtual IActionResult ContactVendorSend(ContactVendorModel model, bool captchaValid)
        {
            if (!_vendorSettings.AllowUsersToContactVendors)
                return RedirectToRoute("HomePage");

            var vendor = EngineContext.Current.Resolve<IVendorService>().GetVendorById(model.VendorId);
            if (vendor == null || !vendor.Active || vendor.Deleted)
                return RedirectToRoute("HomePage");

            //validate CAPTCHA
            if (_captchaSettings.Enabled && _captchaSettings.ShowOnContactUsPage && !captchaValid)
            {
                ModelState.AddModelError("", _captchaSettings.GetWrongCaptchaMessage(_localizationService));
            }

            model.VendorName = vendor.GetLocalized(x => x.Name);

            if (ModelState.IsValid)
            {
                model = _commonWebService.SendContactVendor(model, vendor);
                return View(model);
            }

            model.DisplayCaptcha = _captchaSettings.Enabled && _captchaSettings.ShowOnContactUsPage;
            return View(model);
        }

        //sitemap page
        [HttpsRequirement(SslRequirement.No)]
        public virtual IActionResult Sitemap()
        {

Zajel.Web/Controllers/OLD/PollController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Zajel.Core;
using Zajel.Core.Domain.Users;
using Zajel.Services.Localization;
using Zajel.Services.Polls;
using Zajel.Web.Services;

namespace Zajel.Web.Controllers
{
    public partial class PollController : BasePublicController
    {
        #region Fields

        private readonly IPollWebService _pollWebService;
        private readonly ILocalizationService _localizationService;
        private readonly IWorkContext _workContext;
        private readonly IPollService _pollService;
        #endregion

        #region Constructors

        public PollController(IPollWebService pollWebService,
            ILocalizationService localizationService,
            IWorkContext workContext,
            IPollService pollService)
        {
            this._pollWebService = pollWebService;
            this._localizationService = localizationService;
            this._workContext = workContext;
            this._pollService = pollService;
        }

        #endregion

        #region Methods

        [HttpPost]
        public virtual IActionResult Vote(string pollAnswerId, string pollId)
        {
            var poll = _pollService.GetPollById(pollId); 
            if (!poll.Published)
                return Json(new
                {
                    error = "Poll is not available",
                });

            var pollAnswer = poll.PollAnswers.FirstOrDefault(x=>x.Id == pollAnswerId);
            if (pollAnswer == null)
                return Json(new
                {
                    error = "No poll answer found with the specified id",
                });


            if (_workContext.CurrentUser.IsGuest() && !poll.AllowGuestsToVote)
                return Json(new
                {
                    error = _localizationService.GetResource("Polls.OnlyRegisteredUsersVote"),
                });

            bool alreadyVoted = _pollService.AlreadyVoted(poll.Id, _workContext.CurrentUser.Id);
            if (!alreadyVoted)
            {
                //vote
                _pollWebService.PollVoting(poll, pollAnswer);
            }

            return Json(new
            {
                html = this.RenderPartialViewToString("_Poll", _pollWebService.PreparePoll(poll, true)),
            });
        }
        
        #endregion

    }
}

Zajel.Web/Views/Shared/Head.cshtml
@*This is here so that if an error doesn't get throw if a theme doesn't have a Shared/Head.cshtml*@

Zajel.Web/Views/Shared/Header.cshtml
<header>
    @await Component.InvokeAsync("Widget", new { widgetZone = "header" })
    <nav class="navbar fixed-top navbar-light bg-faded navUp p-0">
        <div class="collapse btn-toolbar generalDropDown" id="generalDropDown">
        </div>
        <div class="container">
            <ul class="nav navbar-nav header-links pl-0 flex-row">
                <li class="nav-item float-xs-right hidden-md-up mr-auto">
                    <a class="btn btn-outlined-info general-opener" data-toggle="collapse" aria-expanded="false" aria-controls="generalDropDown">
                        <span class="fa fa-cogs" aria-hidden="true"></span>
                    </a>
                </li>
                <li class="nav-item float-xs-right hidden-sm-down mr-auto">
                    <div class="generalDropDown btn-toolbar float-xs-right ">
                        <div class="settingSellector">
                            @await Component.InvokeAsync("TaxTypeSelector")
                            @await Component.InvokeAsync("CurrencySelector")
                            @await Component.InvokeAsync("LanguageSelector")
                        </div>
                    </div>
                </li>
                @await Component.InvokeAsync("HeaderLinks")
            </ul>
        </div>
    </nav>
    <div class="headBottom d-md-inline-flex d-sm-grid text-md-left text-center mt-3 mb-3">
        <div class="col header-logo pr-0 pl-0">
            @await Component.InvokeAsync("Logo")
        </div>
        <div class="col formSearch pr-0 pl-0">
            @await Component.InvokeAsync("SearchBox")
        </div>
    </div>
    <script>
        $(document).ready(function () {
            $(".settingSellector").appendTo(".generalDropDown");
        });
    </script>
</header>

Zajel.Web/Views/Shared/_AddressAttributes.cshtml
@model IList<AddressAttributeModel>
@foreach (var attribute in Model)
{
    string controlId = string.Format("address_attribute_{0}", attribute.Id);
    string textPrompt = attribute.Name;

    <div class="inputs custom-attributes col-sm-12">
        <label for="@(controlId)">@textPrompt:</label>
        
        @switch (attribute.AttributeControlType)
        {
            case AttributeControlType.DropdownList:
            {
            <select class="custom-selec form-control" name="@(controlId)" id="@(controlId)">
                @if (!attribute.IsRequired)
                    {
                    <option value="0">---</option>
                    }
                @foreach (var attributeValue in attribute.Values)
                    {
                    <option selected="@attributeValue.IsPreSelected" value="@attributeValue.Id">@attributeValue.Name</option>
                    }
            </select>
            }
                break;
            case AttributeControlType.RadioList:
            {
            <ul class="option-list pl-0">
                @foreach (var attributeValue in attribute.Values)
                    {
                    <li>

                        <label for="@(controlId)_@(attributeValue.Id)" class="custom-control custom-radio">
                            <input class="custom-control-input" id="@(controlId)_@(attributeValue.Id)" type="radio" name="@(controlId)" value="@attributeValue.Id" checked="@attributeValue.IsPreSelected" />
                            <span class="custom-control-indicator"></span>
                            <span class="custom-control-description">@attributeValue.Name</span>
                        </label>

                    </li>
                    }
            </ul>
            }
                break;
            case AttributeControlType.Checkboxes:
            case AttributeControlType.ReadonlyCheckboxes:
            {
            <ul class="option-list pl-0">
                @foreach (var attributeValue in attribute.Values)
                    {
                    <li>
                        <label class="custom-control custom-checkbox">
                            <input class="custom-control-input" id="@(controlId)_@(attributeValue.Id)" type="checkbox" name="@(controlId)" value="@attributeValue.Id" checked="@attributeValue.IsPreSelected" @(attribute.AttributeControlType == AttributeControlType.ReadonlyCheckboxes ? Html.Raw(" disabled=\"disabled\"") : null) />
                            <span class="custom-control-indicator"></span>
                            <span class="custom-control-description">@attributeValue.Name</span>
                        </label>
                    </li>
                    }
            </ul>
            }
            break;
            case AttributeControlType.TextBox:
            {
                <input name="@(controlId)" type="text" class="form-control textbox" id="@(controlId)" value="@attribute.DefaultValue" />
            }
            break;
            case AttributeControlType.MultilineTextbox:
            {
            <textarea class="form-control" id="@(controlId)" name="@(controlId)">@attribute.DefaultValue</textarea>
                }
                break;
            case AttributeControlType.Datepicker:
            case AttributeControlType.FileUpload:
            case AttributeControlType.ColorSquares:
            case AttributeControlType.ImageSquares:
                {
                    //not support attribute type
                }
                break;
        }
    </div>
}

Zajel.Web/Views/Shared/_CategoryLine.TopMenu.cshtml
@model TopMenuModel.CategoryLineModel
<li class="@(Model.Category.SubCategories.Count() == 0 ? "nav-item": "nav-item dropdown" )">

    @if (Model.Category.SubCategories.Count() > 0)
            {
        <span class="fa fa-angle-down hidden-lg-up text-white" aria-hidden="true"></span>
    }

    <a class="pr-3 pl-3 @(Model.Category.SubCategories.Count() == 0 ? "nav-link": "nav-link dropdown-toggle" )  @(Model.Category.IncludeInTopMenu ? "": "hidden-lg-up")" href="@Url.RouteUrl("Category", new { SeName = Model.Category.SeName })">
        @Model.Category.Name
    </a>
    @{
        //subcategories
        var subCategories =
            Model.Category.SubCategories.Where(x => x.IncludeInTopMenu).ToList();

        var levelClass = "";
        if (Model.Level == 0)
        {
            levelClass = "first-level";
            if (subCategories.Any())
            {
                <ul class="dropdown-menu @levelClass">
                    @foreach (var subCategory in subCategories)
                    {
                        var categoryLineModel = new TopMenuModel.CategoryLineModel
                        {
                            Category = subCategory,
                            Level = Model.Level + 1,
                            ResponsiveMobileMenu = Model.ResponsiveMobileMenu
                        };
                        @await Html.PartialAsync("_CategoryLine.TopMenu", categoryLineModel)
                    }
                </ul>
            }
        }
        if (Model.Level == 1 && subCategories.Any())
        {
            levelClass = "next-level";
            <ul class="dropdown-menu @levelClass">
                @foreach (var subCategory in subCategories)
                {
                    var categoryLineModel = new TopMenuModel.CategoryLineModel
                    {
                        Category = subCategory,
                        Level = Model.Level + 1,
                        ResponsiveMobileMenu = Model.ResponsiveMobileMenu
                    };
                    @await Html.PartialAsync("_CategoryLine.TopMenu", categoryLineModel)
                }
            </ul>
        }
    }
</li>

Zajel.Web/Views/Shared/_ColumnsOne.cshtml
@{
    Layout = "_Root.cshtml";
}
@if (IsSectionDefined("Breadcrumb"))
{
    @section Breadcrumb {
        @RenderSection("Breadcrumb")
    }
}

@await Component.InvokeAsync("Widget", new { widgetZone = "main_column_before" })
@RenderBody()
@await Component.InvokeAsync("Widget", new { widgetZone = "main_column_after" })

Zajel.Web/Views/Shared/_Notifications.cshtml
@using Microsoft.AspNetCore.Http
@using Microsoft.Net.Http.Headers
@using System.Text.Encodings.Web;
@inject IHttpContextAccessor httpContextAccessor
@{
    Html.AddScriptParts("~/Scripts/public.actions.js");
    Html.AddScriptParts("~/Scripts/jquery.magnific-popup.min.js");
    Html.AddCssFileParts("~/Content/magnific-popup/magnific-popup.css");

    //success messages
    var successMessages = new List<string>();
    if (TempData[string.Format("Zajel.notifications.{0}", NotifyType.Success)] != null)
    {
        successMessages.AddRange(TempData[string.Format("Zajel.notifications.{0}", NotifyType.Success)] as IList<string>);
    }
    if (ViewData[string.Format("Zajel.notifications.{0}", NotifyType.Success)] != null)
    {
        successMessages.AddRange(ViewData[string.Format("Zajel.notifications.{0}", NotifyType.Success)] as IList<string>);
    }

    //error messages
    var errorMessages = new List<string>();
    if (TempData[string.Format("Zajel.notifications.{0}", NotifyType.Error)] != null)
    {
        errorMessages.AddRange(TempData[string.Format("Zajel.notifications.{0}", NotifyType.Error)] as IList<string>);
    }
    if (ViewData[string.Format("Zajel.notifications.{0}", NotifyType.Error)] != null)
    {
        errorMessages.AddRange(ViewData[string.Format("Zajel.notifications.{0}", NotifyType.Error)] as IList<string>);
    }
}
@foreach (var message in successMessages)
{
    <script type="text/javascript">
        $(document).ready(function () {
            displayPopupNotification('@Html.Raw(JavaScriptEncoder.Default.Encode(message))', 'success', false);
        });
    </script>
}
@foreach (var message in errorMessages)
{
    <script type="text/javascript">
        $(document).ready(function () {
            displayPopupNotification('@Html.Raw(JavaScriptEncoder.Default.Encode(message))', 'error', false);
        });
    </script>
}
<div class="ajax-loading-block-window" style="display: none">
</div>

<div id="bar-notification" class="generalNote card card-inverse text-xs-center" style="display:none;">
    <span class="close" title="@T("Common.Close")"><span class="fa fa-times" aria-hidden="true"></span></span>
</div>

<a class="popup-action-banner" data-mfp-src="#action_modal_banner" style="display:none"></a>
<div id="action_modal_banner" class="zoom-anim-dialog mfp-hide">
    <div id="action-body-banner"></div>
</div>
<a class="popup-action-form" data-mfp-src="#action_modal_form" style="display:none"></a>
<div id="action_modal_form" class="zoom-anim-dialog mfp-hide">
    <form asp-route="PopupInteractiveForm" method="post" id = "interactive-form">
        <div class="message-error">
            <div class="validation-summary-errors">
                <div id="errorMessages"></div>
            </div>
        </div>
        <div id="action-body-form"></div>
        <div style="padding: 20px 0px 0px 0px;">
            <input type="submit" id="send-interactive-form" class="btn btn-success interactive-form-button" value="@T("PopupInteractiveForm.Send")" />
        </div>
    </form>
</div>

<script>
    $(document).ready(function () {
        UserAction.init('@Url.Action("UserActionEventUrl", "Common")', '@Url.Action("GetActivePopup", "Common")', '@Url.Action("RemovePopup", "Common")');
        UserAction.checkActiveUrl('@httpContextAccessor.HttpContext.Request.Path.ToString()', '@httpContextAccessor.HttpContext.Request.Headers[HeaderNames.Referer]');
    });
</script>

@await Component.InvokeAsync("Widget", new { widgetZone = "notifications" })

Zajel.Web/Views/Shared/_Print.cshtml
@using Zajel.Core.Infrastructure
@using Zajel.Framework.Themes
@{
    var themeName = EngineContext.Current.Resolve<IThemeContext>().WorkingThemeName;
}
<!DOCTYPE html>
<html>
<head>
    <title>@Html.ZajelTitle(true)</title>
    <meta http-equiv="Content-type" content="text/html;charset=UTF-8" />
    <link href="@Url.Content(string.Format("~/Themes/{0}/Content/css/print.css", themeName))" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.10.2.min.js")" type="text/javascript"></script>
</head>
<body>
    @RenderBody()
</body>
</html>