Zajel.Web/Areas/Admin/Controllers/OLD/ManufacturerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Zajel.Framework.Mvc.Filters;
using Zajel.Framework.Extensions;
using System;
using System.Collections.Generic;
using System.Linq;
using Zajel.Web.Areas.Admin.Extensions;
using Zajel.Web.Areas.Admin.Models.Catalog;
using Zajel.Core;
using Zajel.Core.Domain.Catalog;
using Zajel.Core.Domain.Discounts;
using Zajel.Services.Catalog;
using Zajel.Services.Users;
using Zajel.Services.Discounts;
using Zajel.Services.ExportImport;
using Zajel.Services.Localization;
using Zajel.Services.Logging;
using Zajel.Services.Media;
using Zajel.Services.Security;
using Zajel.Services.Seo;
using Zajel.Services.Stores;
using Zajel.Services.Vendors;
using Zajel.Framework.Controllers;
using Zajel.Framework.Kendoui;
using Zajel.Framework.Mvc;
using Zajel.Core.Domain.Localization;
using Zajel.Services.Helpers;
using Microsoft.AspNetCore.Http;
using System.Text;

namespace Zajel.Web.Areas.Admin.Controllers
{
    public partial class ManufacturerController : BaseAdminController
    {
        #region Fields

        private readonly ICategoryService _categoryService;
        private readonly IManufacturerService _manufacturerService;
        private readonly IManufacturerTemplateService _manufacturerTemplateService;
        private readonly IProductService _productService;
        private readonly IUserService _userService;
        private readonly IStoreService _storeService;
        private readonly IStoreMappingService _storeMappingService;
        private readonly IUrlRecordService _urlRecordService;
        private readonly IPictureService _pictureService;
        private readonly ILanguageService _languageService;
        private readonly ILocalizationService _localizationService;
        private readonly IExportManager _exportManager;
        private readonly IDiscountService _discountService;
        private readonly IUserActivityService _userActivityService;
        private readonly IVendorService _vendorService;
        private readonly IAclService _aclService; 
        private readonly IPermissionService _permissionService;
        private readonly IDateTimeHelper _dateTimeHelper;
        private readonly IWorkContext _workContext;
        private readonly IImportManager _importManager;
        private readonly CatalogSettings _catalogSettings;

        #endregion
        
        #region Constructors

        public ManufacturerController(ICategoryService categoryService, 
            IManufacturerService manufacturerService,
            IManufacturerTemplateService manufacturerTemplateService,
            IProductService productService,
            IUserService userService, 
            IStoreService storeService,
            IStoreMappingService storeMappingService,
            IUrlRecordService urlRecordService, 
            IPictureService pictureService,
            ILanguageService languageService, 
            ILocalizationService localizationService,
            IExportManager exportManager,
            IDiscountService discountService,
            IUserActivityService userActivityService, 
            IVendorService vendorService,
            IAclService aclService,
            IPermissionService permissionService,
            IDateTimeHelper dateTimeHelper,
            IWorkContext workContext,
            IImportManager importManager,
            CatalogSettings catalogSettings)
        {
            this._categoryService = categoryService;
            this._manufacturerTemplateService = manufacturerTemplateService;
            this._manufacturerService = manufacturerService;
            this._productService = productService;
            this._userService = userService;
            this._storeService = storeService;
            this._storeMappingService = storeMappingService;
            this._urlRecordService = urlRecordService;
            this._pictureService = pictureService;
            this._languageService = languageService;
            this._localizationService = localizationService;
            this._exportManager = exportManager;
            this._discountService = discountService;
            this._userActivityService = userActivityService;
            this._vendorService = vendorService;
            this._aclService = aclService;
            this._permissionService = permissionService;
            this._dateTimeHelper = dateTimeHelper;
            this._workContext = workContext;
            this._importManager = importManager;
            this._catalogSettings = catalogSettings;
        }

        #endregion
        
        #region Utilities

        [NonAction]
        protected virtual List<LocalizedProperty> UpdateLocales(Manufacturer manufacturer, ManufacturerModel model)
        {
            List<LocalizedProperty> localized = new List<LocalizedProperty>();

            foreach (var local in model.Locales)
            {
                if (!(String.IsNullOrEmpty(local.Description)))
                    localized.Add(new LocalizedProperty()
                    {
                        LanguageId = local.LanguageId,
                        LocaleKey = "Description",
                        LocaleValue = local.Description,
                    });
                
                if (!(String.IsNullOrEmpty(local.MetaDescription)))
                    localized.Add(new LocalizedProperty()
                    {
                        LanguageId = local.LanguageId,
                        LocaleKey = "MetaDescription",
                        LocaleValue = local.MetaDescription,
                    });

                if (!(String.IsNullOrEmpty(local.MetaKeywords)))
                    localized.Add(new LocalizedProperty()
                    {
                        LanguageId = local.LanguageId,
                        LocaleKey = "MetaKeywords",
                        LocaleValue = local.MetaKeywords,
                    });

                if (!(String.IsNullOrEmpty(local.MetaTitle)))
                    localized.Add(new LocalizedProperty()
                    {
                        LanguageId = local.LanguageId,
                        LocaleKey = "MetaTitle",
                        LocaleValue = local.MetaTitle,
                    });

                if (!(String.IsNullOrEmpty(local.Name)))
                    localized.Add(new LocalizedProperty()
                    {
                        LanguageId = local.LanguageId,
                        LocaleKey = "Name",
                        LocaleValue = local.Name,
                    });
               
                //search engine name
                var seName = manufacturer.ValidateSeName(local.SeName, local.Name, false);
                _urlRecordService.SaveSlug(manufacturer, seName, local.LanguageId);

                if (!(String.IsNullOrEmpty(seName)))
                    localized.Add(new LocalizedProperty()
                    {
                        LanguageId = local.LanguageId,
                        LocaleKey = "SeName",
                        LocaleValue = seName,
                    });
            }
            return localized;
        }

        [NonAction]
        protected virtual void UpdatePictureSeoNames(Manufacturer manufacturer)
        {
            var picture = _pictureService.GetPictureById(manufacturer.PictureId);
            if (picture != null)
                _pictureService.SetSeoFilename(picture.Id, _pictureService.GetPictureSeName(manufacturer.Name));
        }

        [NonAction]
        protected virtual void PrepareTemplatesModel(ManufacturerModel model)
        {
            if (model == null)
                throw new ArgumentNullException("model");

            var templates = _manufacturerTemplateService.GetAllManufacturerTemplates();
            foreach (var template in templates)
            {
                model.AvailableManufacturerTemplates.Add(new SelectListItem
                {
                    Text = template.Name,
                    Value = template.Id.ToString()
                });
            }
        }

        [NonAction]
        protected virtual void PrepareDiscountModel(ManufacturerModel model, Manufacturer manufacturer, bool excludeProperties)
        {
            if (model == null)
                throw new ArgumentNullException("model");

            model.AvailableDiscounts = _discountService
                .GetAllDiscounts(DiscountType.AssignedToManufacturers, showHidden: true)
                .Select(d => d.ToModel())
                .ToList();

            if (!excludeProperties && manufacturer != null)
            {
                model.SelectedDiscountIds = manufacturer.AppliedDiscounts.ToArray();
            }
        }

        [NonAction]
        protected virtual void PrepareAclModel(ManufacturerModel model, Manufacturer manufacturer, bool excludeProperties)
        {
            if (model == null)
                throw new ArgumentNullException("model");

            model.AvailableUserRoles = _userService
                .GetAllUserRoles(true)
                .Select(cr => cr.ToModel())
                .ToList();
            if (!excludeProperties)
            {
                if (manufacturer != null)
                {
                    model.SelectedUserRoleIds = manufacturer.UserRoles.ToArray();
                }
            }
        }

        

        [NonAction]
        protected virtual void PrepareStoresMappingModel(ManufacturerModel model, Manufacturer manufacturer, bool excludeProperties)
        {
            if (model == null)
                throw new ArgumentNullException("model");

            model.AvailableStores = _storeService
                .GetAllStores()
                .Select(s => s.ToModel())
                .ToList();
            if (!excludeProperties)
            {
                if (manufacturer != null)
                {
                    model.SelectedStoreIds = manufacturer.Stores.ToArray();
                }

Zajel.Web/Areas/Admin/Views/Manufacturer/List.cshtml
@model ManufacturerListModel
@{
    var defaultGridPageSize = EngineContext.Current.Resolve<Zajel.Core.Domain.Common.AdminAreaSettings>().DefaultGridPageSize;
    var gridPageSizes = EngineContext.Current.Resolve<Zajel.Core.Domain.Common.AdminAreaSettings>().GridPageSizes;

    //page title
    ViewBag.Title = T("Admin.Catalog.Manufacturers").Text;
}
@Html.AntiForgeryToken()
<div class="row">
    <div class="col-md-12">
        <div class="portlet light form-fit">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-building-o"></i>
                    @T("Admin.Catalog.Manufacturers")
                </div>
                <div class="actions btn-group btn-group-devided util-btn-margin-bottom-5">
                    <a href="@Url.Action("Create")" class="btn green"><i class="fa fa-plus"></i><span class="hidden-xs"> @T("Admin.Common.AddNew") </span></a>
                    <a href="@Url.Action("ExportXml")" class="btn default">
                        <i class="fa fa-file-code-o"></i> @T("Admin.Common.ExportToXml")
                    </a>
                    <a href="@Url.Action("ExportXlsx")" class="btn default">
                        <i class="fa fa-file-excel-o"></i> @T("Admin.Common.ExportToExcel")
                    </a>
                    <button type="button" id="importexcel" name="importexcel" class="btn blue">
                        <i class="fa fa-upload"></i>
                        @T("Admin.Common.ImportFromExcel")
                    </button>
                </div>
            </div>
            <div class="portlet-body form">
                <div class="form-horizontal">
                    <div class="form-body">
                        <div class="form-group">
                            @Html.ZajelLabelFor(model => model.SearchManufacturerName)
                            <div class="col-md-4 col-sm-6">
                                @Html.ZajelEditorFor(model => model.SearchManufacturerName)
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.ZajelLabelFor(model => model.SearchStoreId)
                            <div class="col-md-4 col-sm-6">
                                @Html.ZajelDropDownListFor(model => model.SearchStoreId, Model.AvailableStores)
                            </div>
                        </div>
                    </div>
                    <div class="form-actions">
                        <div class="row">
                            <div class="col-md-offset-3 col-sm-offset-3 col-md-9 col-sm-9">
                                <button class="btn btn-success filter-submit" id="search-manufacturers">
                                    <i class="fa fa-search"></i> @T("Admin.Common.Search")
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="portlet-body">
                <div id="manufacturers-grid"></div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $("#manufacturers-grid").kendoGrid({
            dataSource: {
                transport: {
                    read: {
                        url: "@Html.Raw(Url.Action("List", "Manufacturer"))",
                        type: "POST",
                        dataType: "json",
                        data: additionalData
                    }
                },
                schema: {
                    data: "Data",
                    total: "Total",
                    errors: "Errors"
                },
                error: function(e) {
                    display_kendoui_grid_error(e);
                    // Cancel the changes
                    this.cancelChanges();
                },
                pageSize: @(defaultGridPageSize),
                serverPaging: true,
                serverFiltering: true,
                serverSorting: true
            },
            pageable: {
                refresh: true,
                pageSizes: [@(gridPageSizes)]
            },
            editable: {
                confirmation: false,
                mode: "inline"
            },
            scrollable: false,
            columns: [{
                field: "Name",
                title: "@T("Admin.Catalog.Manufacturers.Fields.Name")"
            }, {
                field: "Published",
                title: "@T("Admin.Catalog.Manufacturers.Fields.Published")",
                width: 100,
                headerAttributes: { style: "text-align:center" },
                attributes: { style: "text-align:center" },
                template: '# if(Published) {# <i class="fa fa-check" aria-hidden="true" style="color:green"></i> #} else {# <i class="fa fa-times" aria-hidden="true" style="color:red"></i> #} #'
            }, {
                field: "DisplayOrder",
                title: "@T("Admin.Catalog.Manufacturers.Fields.DisplayOrder")",
                width: 120
            }, {
                field: "Id",
                title: "@T("Admin.Common.Edit")",
                width: 80,
                template: '<a class="btn btn-sm btn-default" href="Edit/#=Id#"><i class="fa fa-pencil"></i> @T("Admin.Common.Edit")</a>'
            }]
        });
    });
</script>
<script type="text/javascript">
    $(document).ready(function () {
        //search button
        $('#search-manufacturers').click(function () {
            //search
            var grid = $('#manufacturers-grid').data('kendoGrid');
            grid.dataSource.page(1); //new search. Set page size to 1
            //grid.dataSource.read(); we already loaded the grid above using "page" function
            return false;
        });

        $("#@Html.FieldIdFor(model => model.SearchManufacturerName)").keydown(function (event) {
            if (event.keyCode == 13) {
                $("#search-manufacturers").click();
                return false;
            }
        });
    });

    function additionalData() {
        var data = {
            SearchManufacturerName: $('#@Html.FieldIdFor(model => model.SearchManufacturerName)').val(),
            SearchStoreId: $('#SearchStoreId').val()
        };
        addAntiForgeryToken(data);
        return data;
    }
</script>
@*import manufacturers form*@
<div class="modal-dialog" id="importexcel-window" style="display:none; padding: 0 10px;">
    @using (Html.BeginForm("ImportFromXlsx", "Category", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <em>@T("Admin.Catalog.Manufacturer.List.ImportFromExcelTip")</em>
        <div class="form-group">
            &nbsp;
        </div>
        <div class="form-group">
            <div class="col-md-3" style="margin-top: 2px; height: 34px; padding-left: 25px;">
                <label class="control-label">
                    @T("Admin.Common.ExcelFile"):
                </label>
            </div>
            <div class="col-md-9">
                <input type="file" id="importexcelfile" name="importexcelfile" />
            </div>
        </div>
        <div class="form-group">
            &nbsp;
        </div>
        <div class="form-group">
            <div class="col-md-2">
                &nbsp;
            </div>
            <div class="col-md-10 text-right mt-10">
                <input type="submit" class="k-button" value="@T("Admin.Common.ImportFromExcel")" />
            </div>
        </div>
    }
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $("#importexcel").click(function (e) {
            e.preventDefault();
            var window = $("#importexcel-window");
            if (!window.data("kendoWindow")) {
                window.kendoWindow({
                    modal: true,
                    title: "@T("Admin.Common.ImportFromExcel")",
                    actions: ["Close"]
                });
            }
            window.data('kendoWindow').center().open();
        });
    });
</script>

Zajel.Web/Areas/Admin/Views/Manufacturer/ProductAddPopup.cshtml
@{
    Layout = "~/Areas/Admin/Views/Shared/_AdminPopupLayout.cshtml";
}
@model ManufacturerModel.AddManufacturerProductModel
@{
    var defaultGridPageSize = EngineContext.Current.Resolve<Zajel.Core.Domain.Common.AdminAreaSettings>().DefaultGridPageSize;
    var gridPageSizes = EngineContext.Current.Resolve<Zajel.Core.Domain.Common.AdminAreaSettings>().GridPageSizes;

    //page title
    ViewBag.Title = T("Admin.Catalog.Manufacturers.Products.AddNew").Text;
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col-md-12">
            <div class="portlet light form-fit">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-cubes"></i>
                        @T("Admin.Catalog.Manufacturers.Products.AddNew")
                    </div>
                </div>
                <div class="portlet-body form">

                    <div class="form-horizontal">
                        <div class="form-body">
                            <div class="form-group">
                                @Html.ZajelLabelFor(model => model.SearchProductName, new Dictionary<string, object> { { "class", "col-sm-3" } })
                                <div class="col-md-9 col-sm-9">
                                    @Html.ZajelEditorFor(model => model.SearchProductName)
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.ZajelLabelFor(model => model.SearchCategoryId, new Dictionary<string, object> { { "class", "col-sm-3" } })
                                <div class="col-md-9 col-sm-9">
                                    @Html.ZajelDropDownListFor(model => model.SearchCategoryId, Model.AvailableCategories)
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.ZajelLabelFor(model => model.SearchManufacturerId, new Dictionary<string, object> { { "class", "col-sm-3" } })
                                <div class="col-md-9  col-sm-9">
                                    @Html.ZajelDropDownListFor(model => model.SearchManufacturerId, Model.AvailableManufacturers)
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.ZajelLabelFor(model => model.SearchStoreId, new Dictionary<string, object> { { "class", "col-sm-3" } })
                                <div class="col-md-9 col-sm-9">
                                    @Html.ZajelDropDownListFor(model => model.SearchStoreId, Model.AvailableStores)
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.ZajelLabelFor(model => model.SearchVendorId, new Dictionary<string, object> { { "class", "col-sm-3" } })
                                <div class="col-md-9 col-sm-9">
                                    @Html.ZajelDropDownListFor(model => model.SearchVendorId, Model.AvailableVendors)
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.ZajelLabelFor(model => model.SearchProductTypeId, new Dictionary<string, object> { { "class", "col-sm-3" } })
                                <div class="col-md-9 col-sm-9">
                                    @Html.ZajelDropDownListFor(model => model.SearchProductTypeId, Model.AvailableProductTypes)
                                </div>
                            </div>
                            <div class="form-actions">
                                <div class="row">
                                    <div class="col-md-offset-1 col-md-11 col-sm-11 btn-group btn-group-devided">
                                        <button class="btn btn-success filter-submit" id="search-products">
                                            <i class="fa fa-search"></i> @T("Admin.Common.Search")
                                        </button>
                                        <button class="btn btn-success" type="submit" name="save" ><i class="fa fa-check"></i> @T("Admin.Common.Save") </button>
                                    </div>
                                </div>
                            </div>
                            <div id="products-grid"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>



    if (ViewBag.RefreshPage == true)
    {
        <script type="text/javascript">
            try {window.opener.document.forms['@(ViewBag.formId)'].@(ViewBag.btnId).click();}
            catch (e){} 
            window.close();
        </script>
       }

    

    <script>
        $(document).ready(function () {
            $("#products-grid").kendoGrid({
                dataSource: {
                    transport: {
                        read: {
                            url: "@Html.Raw(Url.Action("ProductAddPopupList", "Manufacturer"))",
                            type: "POST",
                            dataType: "json",
                            data: additionalData
                        }
                    },
                    schema: {
                        data: "Data",
                        total: "Total",
                        errors: "Errors"
                    },
                    error: function(e) {
                        display_kendoui_grid_error(e);
                        // Cancel the changes
                        this.cancelChanges();
                    },
                    pageSize: @(defaultGridPageSize),
                    serverPaging: true,
                    serverFiltering: true,
                    serverSorting: true
                },
                pageable: {
                    refresh: true,
                    pageSizes: [@(gridPageSizes)]
                },
                editable: {
                    confirmation: false,
                    mode: "inline"
                },
                scrollable: false,
                columns: [{
                    field: "Id",
                    headerTemplate: "<input id='mastercheckbox' type='checkbox'/>",
                    headerAttributes: { style: "text-align:center" },
                    template: "<input type='checkbox' name='SelectedProductIds' value='#=Id#' class='checkboxGroups' />",
                    attributes: {
                        style: "text-align:center"
                    },
                    width: 50
                }, {
                    field: "Name",
                    title: "@T("Admin.Catalog.Products.Fields.Name")"
                }, {
                    field: "Published",
                    title: "@T("Admin.Catalog.Products.Fields.Published")",
                    width: 100,
                    headerAttributes: { style: "text-align:center" },
                    attributes: { style: "text-align:center" },
                    template: '# if(Published) {# <i class="fa fa-check" aria-hidden="true" style="color:green"></i> #} else {# <i class="fa fa-times" aria-hidden="true" style="color:red"></i> #} #'
                }]
            });
        });
    </script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#search-products').click(function () {
                var grid = $('#products-grid').data('kendoGrid');
                grid.dataSource.page(1); //new search. Set page size to 1
                //grid.dataSource.read(); we already loaded the grid above using "page" function
                //clear selected checkboxes
                $('.checkboxGroups').prop('checked', false).change();
                return false;
            });

            $("#@Html.FieldIdFor(model => model.SearchProductName)").keydown(function (event) {
                if (event.keyCode == 13) {
                    $("#search-products").click();
                    return false;
                }
            });
                        
            //wire up checkboxes
            $('#mastercheckbox').click(function() {
                $('.checkboxGroups').prop('checked', $(this).is(':checked')).change();
            });

            $('#products-grid').on('change', 'input[type=checkbox][id!=mastercheckbox]', function(e) {
                updateMasterCheckbox();
            });
        });

        function additionalData() {
            var data = {
                SearchProductName: $('#@Html.FieldIdFor(model => model.SearchProductName)').val(),
                SearchCategoryId: $('#SearchCategoryId').val(),
                SearchManufacturerId: $('#SearchManufacturerId').val(),
                SearchStoreId: $('#SearchStoreId').val(),
                SearchVendorId: $('#SearchVendorId').val(),
                SearchProductTypeId: $('#SearchProductTypeId').val()
            };
            addAntiForgeryToken(data);
            return data;
        }

        function updateMasterCheckbox() {
            var numChkBoxes = $('#products-grid input[type=checkbox][id!=mastercheckbox]').length;
            var numChkBoxesChecked = $('#products-grid input[type=checkbox][id!=mastercheckbox]:checked').length;
            $('#mastercheckbox').prop('checked', numChkBoxes == numChkBoxesChecked && numChkBoxes > 0);
        }
    </script>
}

Zajel.Web/Areas/Admin/Views/Manufacturer/_CreateOrUpdate.TabActivityLog.cshtml
@model ManufacturerModel
@{
    var defaultGridPageSize = EngineContext.Current.Resolve<Zajel.Core.Domain.Common.AdminAreaSettings>
    ().DefaultGridPageSize;
    var gridPageSizes = EngineContext.Current.Resolve<Zajel.Core.Domain.Common.AdminAreaSettings>
        ().GridPageSizes;


    <div class="panel panel-default">
        <div class="panel-body">
            <div id="activitylog-grid"></div>
        </div>
    </div>
        <script>
        $(document).ready(function () {
            $("#activitylog-grid").kendoGrid({
                dataSource: {
                    transport: {
                        read: {
                            url: "@Html.Raw(Url.Action("ListActivityLog", "Manufacturer", new { manufacturerId = Model.Id }))",
                            type: "POST",
                            dataType: "json",
                            data: addAntiForgeryToken
                        }
                    },
                    schema: {
                        data: "Data",
                        total: "Total",
                        errors: "Errors"
                    },
                    error: function(e) {
                        display_kendoui_grid_error(e);
                        // Cancel the changes
                        this.cancelChanges();
                    },
                    pageSize: @(defaultGridPageSize),
                    serverPaging: true,
                    serverFiltering: true,
                    serverSorting: true
                },
                pageable: {
                    refresh: true,
                    pageSizes: [@(gridPageSizes)]
                },
                editable: {
                    confirmation: false,
                    mode: "inline"
                },
                scrollable: false,
                columns: [{
                    field: "ActivityLogTypeName",
                    title: "@T("Admin.Catalog.Manufacturers.ActivityLog.ActivityLogType")",
                    width: 200,
                }, {
                    field: "UserId",
                    title: "@T("Admin.Catalog.Manufacturers.ActivityLog.User")",
                    width: 200,
                    template: '<a href="@Url.Content("~/Admin/User/Edit/")#=UserId#">#:UserEmail#</a>'
                }, {
                    field: "Comment",
                    title: "@T("Admin.Catalog.Manufacturers.ActivityLog.Comment")"
                }, {
                    field: "CreatedOn",
                    title: "@T("Admin.Catalog.Manufacturers.ActivityLog.CreatedOn")",
                    width: 200,
                    type: "date",
                    format: "{0:G}"
                }]
            });
        });
        </script>

}

Zajel.Web/Areas/Admin/Views/Manufacturer/_CreateOrUpdate.TabDiscounts.cshtml
@model ManufacturerModel
@{
    if (Model.AvailableDiscounts != null && Model.AvailableDiscounts.Count > 0)
    {
        <div class="mt-checkbox-list">
            @foreach (var discount in Model.AvailableDiscounts)
            {
                <label class="mt-checkbox mt-checkbox-outline">
                    <input type="checkbox" name="SelectedDiscountIds" value="@discount.Id"
                           @if (Model.SelectedDiscountIds != null && Model.SelectedDiscountIds.Contains(discount.Id)) { <text> checked="checked" </text>   } />@discount.Name
                        <span></span>
                    </label>
            }
        </div>
    }
    else
    {
        <div class="note note-info">
            @T("Admin.Catalog.Manufacturers.Discounts.NoDiscounts")
        </div>
    }
}